name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

    - name: Install twilio-cli
      run: | 
        npm install -D twilio-cli 
        npx twilio profiles:add cloudasia

    - name: Install twilio-cli
      run: npx twilio phone-numbers:list

    - name: Install twilio Serverless plugin
      run: npm twilio plugins:install @twilio-labs/plugin-serverless
      
    - name: Deploy to Serverless
      run: npx twilio serverless:list
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
