name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install twilio-cli
      run: npm install -D twilio-cli 

    - name: Install twilio Serverless plugin
      run: npx twilio plugins:install @twilio-labs/plugin-serverless
      
    - name: Provision New Phone Number
      run: |
        PHONE_NUMBER=$(npx twilio api:core:incoming-phone-numbers:create --area-code="704" -o json | jq -r '.[0] | .phoneNumber')
        echo "Phone Number: $PHONE_NUMBER"
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

    - name: Deploy to Serverless
      run: | 
        DEPLOY_URL=$(npx twilio serverless:deploy --force | grep -o "https://(.*)")
        echo "Deploy URL: $DEPLOY_URL"
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      
