name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install twilio-cli
      run: npm install -D twilio-cli 

    - name: Install twilio Serverless plugin
      run: npx twilio plugins:install @twilio-labs/plugin-serverless
      
    - name: Provision New Phone Number
      run: npx twilio api:core:incoming-phone-numbers --area-code="704"
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

    - name: Deploy to Serverless
      run: npx twilio serverless:deploy
      
