name: dev-ci-cd

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install twilio-cli
      run: npm install -D twilio-cli 

    - name: Install twilio Serverless plugin
      run: npx twilio plugins:install @twilio-labs/plugin-serverless
      
    - name: Provision Number, Deploy to Serverless
      run: | 
        DEPLOY_RESULT=$(npx twilio serverless:deploy --force)
        echo "Deploy Result $DEPLOY_RESULT"

        echo "Locating Deploy URL"
        DEPLOY_URL=$(echo $DEPLOY_RESULT | grep -oE "https:\/\/[A-Za-z0-9-]*.twil.io\/[A-Za-z0-9-]*")
        echo "Deploy URL: $DEPLOY_URL"

        echo "Provision New Phone Number"
        PHONE_NUMBER=$(npx twilio api:core:available-phone-numbers:mobile:list --country-code="SG" -o json | jq -r '.[0] | .phoneNumber')
        echo "Phone Number: $PHONE_NUMBER"

        echo "Aquiring Phone Number"
        npx twilio api:core:incoming-phone-numbers:create --phone-number="$PHONE_NUMBER" --identity-sid="$IDENTITY_SID" --address-sid="$ADDRESS_SID" --sms-url="$DEPLOY_URL"
        echo "Phone Number Aquired"
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        IDENTITY_SID: ${{ secrets.IDENTITY_SID }}
        ADDRESS_SID: ${{ secrets.ADDRESS_SID }}
      
#       npx twilio phone-numbers:update $PHONE_NUMBER --sms-url="$DEPLOY_URL"
#       PHONE_NUMBER=$(npx twilio api:core:incoming-phone-numbers:create --area-code="704" -o json | jq -r '.[0] | .phoneNumber')